inputs:
  coloc: gs://genetics-portal-dev-data/22.02.4/outputs/v2d_coloc
  genes: gs://genetics-portal-dev-data/22.02.4/outputs/lut/genes-index

outputs:
  feature_matrix: gs://ot-team/irene/l2g/feature_matrix
  classifier: gs://ot-team/irene/l2g/xgboost_classifier
  predictions: gs://ot-team/irene/l2g/l2g_predictions

intermediate:
  coloc: 'coloc'
  genes: 'genes'

prioritise_genes:
  feature_matrix: gs://genetics-portal-dev-staging/l2g/220212/gold_standards/featurematrix_w_goldstandards.full.220212.parquet
  model: gs://genetics-portal-dev-staging/l2g/220128/models/xgboost-full_model-high_medium-0.model.joblib.gz